### ISSUE TITLE
Cursor Animation lags and not always working after updating to v0.17.2

### ISSUE THREAD

**Issue by MohammedKHC** [Rosemoe/sora-editor#268]
For example when you click on a line the animation will not always work.
+ Please note that i jump from v0.16.5 to v0.17.2 so i don't do if this bug was on an version before v0.17.2

Off Topic question: what is the min sdk required to use this library (if i don't use textmate)

**Comment by Rosemoe** [comment]
What cursor animation are you using? And probably a video containing the bug?

The editor should be used on Android API 21 or above. Textmate can be desugared with l8 to run on API 21. If you use editor-lsp, API 26 is required.

**Comment by MohammedKHC** [comment]
@Rosemoe will you fix that, and does this happened to you too?

**Comment by Rosemoe** [comment]
> @Rosemoe will you fix that, and does this happened to you too?

This is actually intended. When composing text is in editor, cursor animator will not be run due to flashes when the composing text is changed.
The old composing text is actually first deleted and then new one is inserted. And thus, the cursor jumps backward and forward.

I'd like to update the animator invocations so that the animation can be correctly run in a approriate way.
