### ISSUE TITLE
Catch OOM exception when paste huge content in editor

### ISSUE THREAD

**Issue by kyze8439690** [Rosemoe/sora-editor#356]
```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 29029928 byte allocation with 16123064 free bytes and 15MB until OOM, target footprint 268435456, growth limit 268435456
       at java.util.Arrays.copyOf(Arrays.java:3257)
       at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
       at java.lang.AbstractStringBuilder.ensureCapacity(AbstractStringBuilder.java:111)
       at java.lang.StringBuilder.ensureCapacity(StringBuilder.java:77)
       at io.github.rosemoe.sora.text.Content.appendToStringBuilder(Content.java:874)
       at io.github.rosemoe.sora.text.Content.toStringBuilder(Content.java:852)
       at io.github.rosemoe.sora.text.Content.toString(Content.java:840)
```

**Comment by kyze8439690** [comment]
Maybe display a toast to prompt user?

**Comment by Rosemoe** [comment]
Could you please send further stacktrace for locating the `toString` operation? Thanks a lot.
I thought this may happen when users copy text instead of pasting text.

**Comment by kyze8439690** [comment]
It is possible to get a stream instead of initializing a huge variable. Sorry for not digging deep into the code.

**Comment by Rosemoe** [comment]
We could probably show a toast when the text length exceeds a pre-set number.

And how about creating some built-in methods related to saving `Content` object to streams and writers? This settles the problem. Also we may add file encoding support for these actions.

**Comment by kyze8439690** [comment]
That is great to have a convenient method to save content to file!

For the toast part, I think it is more flexible to explicitly throw an exception related to the OOM issue in `toString()` method, library integrator can catch this exception and do whatever they want.

**Comment by kyze8439690** [comment]
If you want to set a pre-define number to content length limit, what value is more appropriate to use? I think devices with different hardware configurations should set different values

**Comment by Rosemoe** [comment]
Applications with `largeHeap` on (got 512MB on newer Android) may use 48MB limit. Devices with lower memory such as 256MB may have a 16MB or 12MB limit. Just a rough data, not tested yet.

The total memory usage in editor can be more than 3*fileSize. Generally, for thread-safe, the highlighting analysis holds a shadow text for reading and handles text changes in queue(if you use tree-sitter the shadowed text is not in VM heap). For text with many lines, due to text storage structure, we may use more extra space for line model object allocations and gap char array space in each line. The `ContentLine` is quite like `StringBuilder`, the capacity doubles when it is exhausted.

Possibly, we'll add paged editting for large files in future so the memory usage can be optimized. But in that mode, code insights may not work well.

**Comment by MuntashirAkon** [comment]
> Possibly, we'll add paged editting for large files in future so the memory usage can be optimized. But in that mode, code insights may not work well.

This is acceptable for large files. Most other IDEs disable those features when they file contains too many lines or incredibly long line(s).
