### ISSUE TITLE
buggy selection and scrolling in ViewPager

### ISSUE THREAD

**Issue by PranavPurwar** [Rosemoe/sora-editor#456]
If you try to select a text and move the selection, the selection cursor doesn't move properly unless you drag it slowly.

Even basic horizontal scrolling is messed up, in order to scroll even a bit, you have to do drag the editor multiple times and sometimes even causes unexpected back navigation

This issue has started since I updated to snapshot build

**Comment by Rosemoe** [comment]
Is that caused by 3d22a20 ?
Could you provide a video to help me understand the problem better? I feel normal when selecting and scrolling.

**Comment by PranavPurwar** [comment]
https://github.com/Rosemoe/sora-editor/assets/75154889/d3ba9c79-e7c2-40a7-944e-e23aa8a7a158

**Comment by Rosemoe** [comment]
I tested and found that in even older version (0.21.1 and 0.20.0), this still happened.

I found that you are using a `ViewPager2` in your layout and this should be the issue. The horizontal scrolling gesture of editor is conflict to its outer layout, ViewPager.
In this case, you need to set an extra property of editor to avoid the mess. Please see `CodeEditor#setInterceptParentHorizontalScrollIfNeeded` for details.

After modifying the interception setting, the horizontal scrolling becomes normal. 
In `IdeEditor.kt`:
```Kotlin
init {
    // ...
    setInterceptParentHorizontalScrollIfNeeded(true)
}
```
However, the issue of selection handles is not settled yet because it is not taken into account when the interception is designed. I'll fix it in a recent commit.

**Comment by Rosemoe** [comment]
Is the issue fixed?

**Comment by PranavPurwar** [comment]
Yup
