### ISSUE TITLE
[Question]: How to Use in project by Source Code

### ISSUE THREAD

**Issue by CyberXCoder-6649** [Rosemoe/sora-editor#512]
How can i include Sora Editor library in my project by Source Code not by dependencies in gradle by adding Source Code in Project i can extend it further according to my need. I've tried doing that but Not Working

Sorry for bad English

Edit: In issue #506 i said to add proper documentation maybe you can also add proper documentation for using Sora Editor by Source Code

**Comment by Rosemoe** [comment]
It can be a little complicated to include the project to your project directly by source code.
We suppose you are using Kotlin Script as your Gradle script instead of Groovy and Version Catalog feature.
You need to copy the modules into your project, and include them by name in the  `settings.gradle.kts` under project root. Also you need to copy `gradle/libs.versions.toml`, where versions of dependencies are stored. Then you need to view `build.gradle.kts` under project root and add some parts of it to yours (probably, with some modification to fit your project), to properly configure editor subprojects.

**Comment by CyberXCoder-6649** [comment]
> It can be a little complicated to include the project to your project directly by source code. We suppose you are using Kotlin Script as your Gradle script instead of Groovy and Version Catalog feature. You need to copy the modules into your project, and include them by name in the `settings.gradle.kts` under project root. Also you need to copy `gradle/libs.versions.toml`, where versions of dependencies are stored. Then you need to view `build.gradle.kts` under project root and add some parts of it to yours (probably, with some modification to fit your project), to properly configure editor subprojects.

Ya i tried that already but it wasn't not compatible with my build tool version so i decided to use it as normally but when it will be necessary i will include source code in my project later
